{{- if (eq .Values.existing_secret_secret1 "") -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
  name: {{ printf "%s-secret1" .Release.Name }}
  namespace: {{ .Release.Namespace }}
data:
  secret1_env_var1: {{ .Values.docker_example.secret1_env_var1 | b64enc | quote }}
  secret1_env_var2: {{ .Values.docker_example.secret1_env_var2 | b64enc | quote }}
{{- end -}}