{{- if (eq .Values.existing_secret_secret2 "") -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
  name: {{ printf "%s-secret2" .Release.Name }}
  namespace: {{ .Release.Namespace }}
data:
  secret2_env_var3: {{ .Values.docker_example.secret2_env_var3 | b64enc | quote }}
{{- end -}}