apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "common.labels.standard" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 8000
    name: http-8000
  - port: 8001
    name: http-8001
  selector:
  {{- include "common.labels.matchLabels" . | nindent 4 }}
