py_package(
    description="Simple module for parsing, modifying, and export `docker-compose` files",
    extras_require={
        "pydantic_v1": ["pydantic>=1.10.2,<=2"],
        "pydantic_v2": ["pydantic>=2.1.1,<=3", "pydantic-settings>=2.0.3"],
    },
)
