[GLOBAL]
pants_version = "2.17.0rc3"
print_stacktrace = true
level = "warn"
build_file_prelude_globs = ["_pants/*.py"]

# for plugin development
pythonpath = ["%(buildroot)s/_pants/pants_py_deploy/src", "%(buildroot)s/compose_chart_export/src", "%(buildroot)s/docker_compose_parser/src", "%(buildroot)s/model_lib/src", "%(buildroot)s/zero_3rdparty/src"]
plugins = [
  "pydevd-pycharm==231.8109.197",
  "PyYAML==6.0.1",
  "pydantic==1.10.2",
  "orjson==3.6.5",
  "semver==2.13.0"
]

backend_packages = [
  "pants.backend.awslambda.python",
  "pants.backend.build_files.fmt.black",
  "pants.backend.codegen.protobuf.python",
  "pants.backend.docker",
  "pants.backend.experimental.helm",
  "pants.backend.experimental.python",
  "pants.backend.experimental.python.lint.ruff",
  "pants.backend.python",
  "pants.backend.python.lint.black",
  "pants.backend.python.mixed_interpreter_constraints",
  "pants.backend.python.typecheck.mypy",
  "pants.backend.plugin_development",
  "pants_py_deploy" # for disabling the plugin, comment this line, and extra fields in py_deploy
]
[anonymous-telemetry]
enabled="false"

[source]
root_patterns = ["/*/src", "/*/", "/*/tests", "/*/test", "/_pants/*/src", "/_pants/*/tests", "/_pants/3rdparty"]

[python]
interpreter_constraints=[">=3.9"]
enable_resolves = true

[python-infer]
use_rust_parser = true
ignored_unowned_imports = ["tomli", "tomli_w"]

[python.resolves]
pants-plugins = "_pants/3rdparty/lock.txt"
pydantic-v1 = "3rdparty/python/pydantic-v1.lock"
python-default = "3rdparty/python/default.lock"

[python.resolves_to_interpreter_constraints]
pants-plugins = [">=3.9,<3.10"]
python-default = [">=3.9"]
pydantic-v1 = [">=3.9"]

[black]
config = "pyproject.toml"
interpreter_constraints = [">=3.11"]

[mypy]
config = "pyproject.toml"
install_from_resolve="python-default"
interpreter_constraints=[">=3.11"]

[ruff]
config ="pyproject.toml"
install_from_resolve="python-default"
interpreter_constraints=[">=3.10"]
# pants doesn't understand 1st party imports since it runs in a different chroot
args = "--ignore=I001"


[coverage-py]
interpreter_constraints = [">=3.9"]
report = ["xml", "html"]
install_from_resolve = "python-default"
requirements = [
  "coverage[toml]>=6.5,<8",
]
config = "pyproject.toml"

[test]
use_coverage = true
extra_env_vars = ["RUNNING_IN_PANTS=yes"]
timeout_default = 30
timeout_maximum = 600

[pytest]
install_from_resolve="python-default"
requirements= [
  "pytest==6.2.5",
  "pytest-asyncio==0.15.1",
  "pytest-cov==3.0.0",
  "pytest-regressions==2.0.1",
  "pytest-freezegun==0.4.2",
  "pytest-html==3.1.1",
  "pytest-subtests==0.5.0",
  "xdoctest==0.15.4",
]

[generate-lockfiles]
diff = true

[python-protobuf]
mypy_plugin = true


[environments-preview.names]
python_bullseye_amd = "//:python_bullseye_amd"
python_bullseye_arm = "//:python_bullseye_arm"
linux_amd = "//:linux_amd"
linux_arm = "//:linux_arm"

[tailor]
ignore_adding_targets=["_pants:_pants", "//:root"]
ignore_paths=["compose_chart_export/tests/test_chart_export/charts/**"]