[project]
name = "py-libs"
version = "1.0.0+rc1"
requires-python = ">=3.10"
dependencies = ["model-lib", "zero-3rdparty"]

[tool.uv]
package = false

[tool.uv.sources]
model-lib = { workspace = true }
zero-3rdparty = { workspace = true }

[tool.uv.workspace]
members = ["model-lib", "zero-3rdparty"]
exclude=['model_lib', 'docker_example', 'compose_chart_export', 'docker_compose_parser']

# [build-system]
# requires = ["hatchling"]
# build-backend = "hatchling.build"

[tool.pytest.ini_options]
testpaths = ["model-lib/model_lib", "zero-3rdparty/zero_3rdparty"]

[dependency-groups]
dev = [
    "attrs>=24.3.0",
    "pytest>=8.3.4",
    "pytest-asyncio==0.15.1",
    "pytest-cov==3.0.0",
    "pytest-regressions==2.0.1",
    "pytest-freezegun==0.4.2",
    "pytest-subtests==0.5.0",
    "xdoctest==0.15.4",
]
