[tool.black]
line-length = 88

[tool.pytest.ini_options]
addopts="--tb=short -vv --xdoc --xdoctest-style=google"
log_cli_level="INFO"
log_cli=true
log_cli_format="%(asctime)s.%(msecs)03d %(levelname)-6s %(threadName)-10s '%(message)-s' %(name)10s.%(funcName)-22s"
junit_logging="all"

[tool.mypy]
warn_return_any = false
ignore_missing_imports = true

[[tool.mypy.overrides]]
module="test_zero_3rdparty.*,test_model_lib.*"
ignore_errors = true

[[tool.mypy.overrides]]
# support for pydantic v1+v2 is hard to satisfy type hints
module="model_lib.pydantic_utils,compose_chart_export.chart_file_templates"
disable_error_code = "import,attr-defined,no-redef,misc,assignment,call-arg"


[tool.ruff]
line-length = 88
target-version="py39"
show-fixes=true
exclude=["_pants/*.py"]
extend-ignore=[ "E501", "UP006", "UP007", "UP035"]
flake8-quotes = {inline-quotes = 'double', multiline-quotes = 'double'}
extend-select = ['Q', 'RUF100', 'C90', 'UP', 'I', 'T']
isort = { known-first-party = ['tests'] }

[tool.ruff.extend-per-file-ignores]
"model_lib/src/model_lib/__init__.py" = ["I001"]
"model_lib/src/model_lib/metadata/__init__.py" = ["I001"]
