# Generated by pkg-ext
from my_pkg._internal import MyCls as _MyCls
from my_pkg._internal import expose as _expose
from my_pkg._internal import expose_with_arg as _expose_with_arg

MyCls = _MyCls
expose = _expose
expose_with_arg = _expose_with_arg
