app_kubernetes_io_name: ''
app_kubernetes_io_instance: ''
podLabels: {}
podAnnotations: {}
nodeSelector: {}
replicas: 1
serviceAccount:
  name: docker-example
  annotations: {}
  create: true
docker_example:
  PORT: '8000'
  env: default
  name: __REQUIRED__
  image: docker-example-amd-docker:latest-amd
