[project]
name = "pytest-model-lib"
version = "0.0.1"
requires-python = ">=3.10"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
include = [
  "pytest_model_lib/*.py",
]
exclude = [
  "*_test.py",
  "conftest.py",
  "test_*.json",
]
