py_package(
    description="base models, metadata, and how to dump them to json|yaml",
    extra_dependencies=["!!//3rdparty#orjson@resolve=python-default"],
    extras_require={"json": ["orjson>=3.6.5"]},
)
