import pytest

from pkg_ext.config import Stability
from pkg_ext.models.groups import PublicGroup, PublicGroups
from pkg_ext.warnings_gen import (
    generate_warnings_content,
    needs_warnings_module,
    to_pascal_case,
)


@pytest.mark.parametrize(
    ("pkg_name", "expected"),
    [
        ("pkg_ext", "PkgExt"),
        ("my_lib", "MyLib"),
        ("simple", "Simple"),
        ("zero_3rdparty", "Zero3rdparty"),
    ],
)
def test_to_pascal_case(pkg_name: str, expected: str):
    assert to_pascal_case(pkg_name) == expected


def test_needs_warnings_module_false_when_all_ga():
    groups = PublicGroups(
        groups=[
            PublicGroup(name="__ROOT__"),
            PublicGroup(name="config", stability=Stability.ga),
        ]
    )
    assert not needs_warnings_module(groups)


def test_needs_warnings_module_true_when_experimental():
    groups = PublicGroups(
        groups=[
            PublicGroup(name="__ROOT__"),
            PublicGroup(name="config", stability=Stability.experimental),
        ]
    )
    assert needs_warnings_module(groups)


def test_needs_warnings_module_true_when_deprecated():
    groups = PublicGroups(
        groups=[
            PublicGroup(name="__ROOT__"),
            PublicGroup(name="legacy", stability=Stability.deprecated),
        ]
    )
    assert needs_warnings_module(groups)


def test_generate_warnings_content_format():
    content = generate_warnings_content("my_pkg")

    assert "class MyPkgWarning(UserWarning):" in content
    assert "class MyPkgExperimentalWarning(MyPkgWarning):" in content
    assert "class MyPkgDeprecationWarning(MyPkgWarning, DeprecationWarning):" in content
    assert "def _experimental(obj: type | F)" in content
    assert "def _experimental_args(*names: str)" in content
    assert "def _deprecated_args(*names: str, **renames: str)" in content
    assert "def _deprecated_arg(" in content
    assert "Auto-generated by pkg-ext" in content
    assert "from warnings import deprecated  # noqa: F401" in content
