name: pants_init

runs:
  using: composite
  steps:
  - uses: actions/checkout@v3
    with:
      token: ${{ secrets.GH_PAT }}
  - name: Initialize Pants
    uses: pantsbuild/actions/init-pants@main
    env:
      GITHUB_TOKEN: ${{ secrets.GH_PAT }}
    with:
      # cache0 makes it easy to bust the cache if needed
      gha-cache-key: cache0-py-3-10
      named-caches-hash: ${{ hashFiles('3rdparty/*.txt') }}