name: pants_init

inputs:
  gh_pat:
    required: true
runs:
  using: composite
  steps:
  - name: Initialize Pants
    uses: pantsbuild/actions/init-pants@main
    env:
      GITHUB_TOKEN: ${{ inputs.gh_pat }}
    with:
      # cache0 makes it easy to bust the cache if needed
      gha-cache-key: cache0-py-3-10
      named-caches-hash: ${{ hashFiles('3rdparty/*.txt') }}