name: setup-steps
description: 'Setup steps for running just commands'

inputs:
  python-version:
    default: '3.13'
    description: 'Python version to use'

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: "${{ inputs.python-version }}"
    - uses: yezz123/setup-uv@v4
      with:
        uv-version: "0.5.15"
    - uses: extractions/setup-just@v2
      with:
        just-version: "1.38.0"
    - uses: hashicorp/setup-terraform@5a8481b19f9c306e74569d1641e269bc213b9f94
      name: configure terraform
      with:
        terraform_version: "1.12.2"
    - name: git-configure
      shell: bash
      run: |
        git config --global user.name github-actions[bot]
        git config --global user.email github-actions[bot]@users.noreply.github.com
