py_package(
    description="compose_agent_export for docker-compose -> helm chart",
    extras_require={
        "pydantic_v1": ["pydantic>=1.10.2,<=2"],
        "pydantic_v2": ["pydantic>=2.1.1,<=3", "pydantic-settings>=2.0.3"],
    },
)
