"""Generate example files for public API functions and classes."""

from __future__ import annotations

from zero_3rdparty.humps import pascalize
from zero_3rdparty.sections import CommentConfig, slug, wrap_section

from pkg_ext.config import Stability
from pkg_ext.models.api_dump import (
    ClassDump,
    ClassFieldInfo,
    FuncParamInfo,
    FunctionDump,
    GroupDump,
    ParamKind,
    SymbolDump,
)
from pkg_ext.pkg_state import PkgExtState

TOOL_NAME = "pkg-ext"
PY_CONFIG = CommentConfig("#")


def _type_str(type_annotation: str | None) -> str:
    return type_annotation or "Any"


def _field_line(name: str, type_annotation: str | None) -> str:
    return f"    {name}: {_type_str(type_annotation)} = ..."


def _skip_param(param: FuncParamInfo) -> bool:
    if param.kind in (ParamKind.VAR_POSITIONAL, ParamKind.VAR_KEYWORD):
        return True
    return param.name == "self"


def _skip_class_field(field: ClassFieldInfo) -> bool:
    return field.is_class_var or field.is_computed


def generate_function_example_class(func: FunctionDump) -> str:
    """Generate Example subclass from FunctionDump.signature.parameters."""
    class_name = f"{pascalize(func.name)}Example"
    fields = [
        _field_line(p.name, p.type_annotation)
        for p in func.signature.parameters
        if not _skip_param(p)
    ]
    fields_str = "\n".join(fields) if fields else "    pass"
    return f"class {class_name}(Example):\n{fields_str}"


def generate_class_example_class(cls: ClassDump) -> str:
    """Generate Example subclass from ClassDump.fields."""
    class_name = f"{pascalize(cls.name)}Example"
    if not cls.fields:
        return f"class {class_name}(Example):\n    pass"
    fields = [
        _field_line(f.name, f.type_annotation)
        for f in cls.fields
        if not _skip_class_field(f)
    ]
    fields_str = "\n".join(fields) if fields else "    pass"
    return f"class {class_name}(Example):\n{fields_str}"


def _symbol_example_class(symbol: SymbolDump) -> str | None:
    match symbol:
        case FunctionDump():
            return generate_function_example_class(symbol)
        case ClassDump():
            return generate_class_example_class(symbol)
    return None


def generate_group_examples_file(group: GroupDump, pkg_import_name: str) -> str:
    """Generate standalone {group}_examples.py content."""
    header = f'''\
"""Example classes for {group.name} group. Generated by pkg-ext."""

from typing import Any

from model_lib.model_base import Entity


class Example(Entity):
    example_name: str
    example_description_md: str = ""'''

    header_section = wrap_section(header, "header", TOOL_NAME, PY_CONFIG)

    sections = [header_section, ""]
    for symbol in group.symbols:
        if class_code := _symbol_example_class(symbol):
            section_id = f"class_{slug(symbol.name)}"
            sections.extend(
                (wrap_section(class_code, section_id, TOOL_NAME, PY_CONFIG), "")
            )

    return "\n".join(sections)


def get_example_stability(
    tool_state: PkgExtState,
    group_name: str,
    symbol_name: str,
    used_args: set[str] | None = None,
) -> Stability:
    """Infer stability from symbol + args used.

    Priority:
    1. Any used arg experimental/deprecated -> that stability
    2. Symbol experimental/deprecated -> that stability
    3. Group stability (defaults to GA)
    """
    if used_args:
        for arg in used_args:
            arg_stability = tool_state.get_arg_stability(group_name, symbol_name, arg)
            if arg_stability != Stability.ga:
                return arg_stability
    symbol_stability = tool_state.get_symbol_stability(group_name, symbol_name)
    if symbol_stability != Stability.ga:
        return symbol_stability
    return tool_state.get_group_stability(group_name)
