"""Generate parameterized test files from example instances."""

from __future__ import annotations

import logging

from zero_3rdparty.humps import pascalize
from zero_3rdparty.sections import CommentConfig, slug, wrap_section

from pkg_ext.models.api_dump import ClassDump, FunctionDump, GroupDump, SymbolDump

logger = logging.getLogger(__name__)

TOOL_NAME = "pkg-ext"
PY_CONFIG = CommentConfig("#")
EXAMPLE_EXCLUDE_FIELDS = '{"example_name", "example_description_md"}'


def _example_class_name(symbol_name: str) -> str:
    return f"{pascalize(symbol_name)}Example"


def _generate_func_test(func: FunctionDump, group_name: str) -> str:
    """Generate parametrize block for a function test."""
    example_class = _example_class_name(func.name)
    var_name = f"{func.name}_examples"

    # Build the function call args from signature parameters
    params = [
        p
        for p in func.signature.parameters
        if p.name != "self" and p.kind not in ("var_positional", "var_keyword")
    ]
    args = ", ".join(f"{p.name}=example.{p.name}" for p in params)

    return f"""\
{var_name} = [e for e in vars(examples_module).values() if isinstance(e, examples_module.{example_class})]

@pytest.mark.parametrize("example", {var_name}, ids=[e.example_name for e in {var_name}])
def test_{func.name}(example: examples_module.{example_class}):
    result = {func.name}({args})"""


def _generate_class_test(cls: ClassDump, group_name: str) -> str:
    """Generate parametrize block for a class test."""
    example_class = _example_class_name(cls.name)
    var_name = f"{slug(cls.name)}_examples"

    return f"""\
{var_name} = [e for e in vars(examples_module).values() if isinstance(e, examples_module.{example_class})]

@pytest.mark.parametrize("example", {var_name}, ids=[e.example_name for e in {var_name}])
def test_{slug(cls.name)}(example: examples_module.{example_class}):
    instance = {cls.name}(**example.model_dump(exclude={EXAMPLE_EXCLUDE_FIELDS}))"""


def _generate_symbol_test(
    symbol: SymbolDump, group_name: str
) -> tuple[str, str] | None:
    """Generate test code and section ID for a symbol. Returns None for non-testable symbols."""
    match symbol:
        case FunctionDump():
            section_id = f"{symbol.name}_test_parametrize"
            return section_id, _generate_func_test(symbol, group_name)
        case ClassDump():
            section_id = f"{slug(symbol.name)}_test_parametrize"
            return section_id, _generate_class_test(symbol, group_name)
    return None


def generate_group_test_file(group: GroupDump, pkg_import_name: str) -> str:
    """Generate {group}_test.py content with parameterized tests."""
    # Collect imports: functions and classes from the group
    func_names = [s.name for s in group.symbols if isinstance(s, FunctionDump)]
    class_names = [s.name for s in group.symbols if isinstance(s, ClassDump)]

    imports: list[str] = []
    if func_names or class_names:
        all_symbols = func_names + class_names
        imports.append(
            f"from {pkg_import_name}.{group.name} import {', '.join(all_symbols)}"
        )

    header = f'''\
"""Parameterized tests for {group.name} group. Generated by pkg-ext."""

import pytest

from {pkg_import_name} import {group.name}_examples as examples_module
{chr(10).join(imports)}'''

    header_section = wrap_section(header, "header", TOOL_NAME, PY_CONFIG)
    sections = [header_section, ""]

    for symbol in group.symbols:
        if result := _generate_symbol_test(symbol, group.name):
            section_id, test_code = result
            sections.extend(
                (wrap_section(test_code, section_id, TOOL_NAME, PY_CONFIG), "")
            )
        else:
            logger.debug(f"Skipping non-testable symbol: {symbol.name}")

    return "\n".join(sections)
