name: docs
on: push

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      deployments: write
      statuses: write
    steps:
      - uses: actions/checkout@v4
      - name: setup-steps
        uses: "./.github/templates/setup-steps"
      - run: just docs "gh-deploy --force"
