name: CI - Typecheck

on:
  push:
    branches:
      - "**"
jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
      - name: pants_init
        uses: "./.github/templates/pants_init"
        with:
          gh_pat: secrets.GH_PAT
      - name: mypy
        run: "pants --tag='-arm' check ::"
